projectName: SkipOnTab
projectUrl: https://joelpurra.com/projects/skipontab/
projectRedirectBaseUrl: https://joelpurra.com/projects/skipontab/docs
projectGithub: https://github.com/joelpurra/skipontab
projectStackoverflow: https://stackoverflow.com/search?q=skipontab
